// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynkyfwpyyhikehzgoxbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlua3lmd3B5eWhpa2VoemdveGJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMDU1NzAsImV4cCI6MjA1Nzc4MTU3MH0.YIfyuQxz_q-jFJq8DxhA1Xk0YwkzUHL-T9foibQ_Iak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);